- name: ensure Supervisor is installed via the system package
  apt:
    name: supervisor
    state: present
    update_cache: yes

- name: create Supervisor template for the WSGI app to run
  template: src=supervisor_app.conf.j2
            dest=/etc/supervisor/conf.d/{{ app_name }}.conf

- name: stop supervisor for app
  service: name=supervisor state=stopped

- name: pause for restart to take effect
  pause: seconds=2

- name: start supervisor for app
  service: name=supervisor state=started
