###
# updates the APT package cache and installs packages
# servers necessary for web. also enables firewall
##

- name: configure locales
  locale_gen: name={{ item }}
  with_items:
    - en_US
    - en_US.UTF-8
    - es_MX
    - es_MX.UTF-8
